In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.16.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
#3. Create a null vector of size 10
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
#4 find the memory size of an array 
Z=np.zeros((10,10))
print(Z.size)
print("%d bytes" % (Z.size * Z.itemsize))

100
800 bytes


In [18]:
#6 Create a null vector of size 10 but the fifth value which is 1 
z=np.zeros(10)
z[5]=1
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
#7Create a vector with values ranging from 10 to 49
z= np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
#8 Reverse a vector (first element becomes last)
#[start:stop:step]

z=z[::-1]
print(z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [22]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
# 10 Find indices of non-zero elements from [1,2,0,0,4,0]

z=np.nonzero([1,2,0,0,4,0])
print(z)


(array([0, 1, 4], dtype=int64),)


In [27]:
#11 Create a 3x3 identity matrix
z = np.eye((3))
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#12 Create a 3x3x3 array with random values 

z=np.random.random((3,3,3))
print(z)


[[[0.63634823 0.60715708 0.22587843]
  [0.77711328 0.01127136 0.33908887]
  [0.65248743 0.56474676 0.6979611 ]]

 [[0.94143235 0.96960997 0.71137058]
  [0.68318555 0.78294619 0.28129981]
  [0.56387215 0.41917231 0.3794679 ]]

 [[0.31529328 0.23263071 0.7267258 ]
  [0.43979758 0.75612405 0.48381558]
  [0.76825185 0.28860352 0.06679151]]]


In [34]:
#13  Create a 10x10 array with random values and find the minimum and maximum values 
z= np.random.random((10,10))
zmin,zmax = z.min(),z.max()
print(zmin,zmax)


0.005460771615501181 0.9953035719645009


In [37]:
# 14 Create a random vector of size 30 and find the mean value
z = np.random.random(30)

m = z.mean()
print(m)

0.4891687228646875


In [56]:
#15 Create a 2d array with 1 on the border and 0 inside 
z = np.ones((10,10))
#print(z)
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [68]:
#16 to add a border (filled with 0's) around an existing array?

z= np.ones((5,5))
#print(z)
z=np.pad(z, pad_width=1, mode='constant', constant_values=0)

print(z)



[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [70]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [74]:

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
print(np.inf)

inf


In [81]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

# Parameters:	
# v : array_like
# If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

# k : int, optional
# Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

# Returns:	
# out : ndarray
# The extracted diagonal or constructed diagonal array.


z=np.arange(4)
print(z)
z=1+np.arange(4)
print(z)
z = np.diag(1+np.arange(4),k=-1)
print(z)

[0 1 2 3]
[1 2 3 4]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [82]:
 

z=np.zeros((8,8))
print(z)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [97]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [98]:
# 20 print(np.unravel_index(99,(6,7,8)))
# https://stackoverflow.com/questions/48135736/what-is-an-intuitive-explanation-of-np-unravel-index
# unravel_index function tell you what should have been the indices of [22, 41, 37] if the array is not flattened
print(np.unravel_index(99,(6,7,8)))



(1, 5, 3)


In [109]:
# 21 Create a checkerboard 8x8 matrix using the tile function 
# numpy.tile(arr, repetitions) : constructs a new array by repeating array – ‘arr’, the number of times
#     we want to repeat as per repetitions. The resulted array will have dimensions max(arr.ndim, repetitions) where, 
#     repetitions is the length of repetitions.
arr = np.arange(5)
print(arr)
z=np.tile(arr,2)
print(z)
z=np.tile( np.array([[0,1],[1,0]]), (2,2))
print(z)

[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [111]:
#Normalize a 5x5 random matrix

z = np.random.random((5,5))
print(z)
z = (z - np.mean (z)) / (np.std (z))
print(z)


[[0.72748014 0.09952223 0.15038276 0.53906783 0.95134665]
 [0.05055943 0.05377039 0.17095929 0.99917658 0.94619743]
 [0.37307662 0.09496147 0.92495208 0.22907558 0.57026739]
 [0.35947344 0.24474949 0.80096662 0.96590261 0.96132678]
 [0.79443544 0.32534273 0.39741732 0.83634598 0.84215042]]
[[ 0.56442015 -1.29004261 -1.13984311  0.00800768  1.22553469]
 [-1.43463777 -1.42515528 -1.07907724  1.36678432  1.2103282 ]
 [-0.48219158 -1.30351128  1.14758719 -0.90745029  0.10014511]
 [-0.52236402 -0.86116266  0.7814378   1.26852083  1.25500766]
 [ 0.76215014 -0.62315759 -0.4103095   0.88591886  0.9030603 ]]


In [118]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

z=1
print(type(z))
print(type(color))


<class 'int'>
<class 'numpy.dtype'>


In [119]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

a = np.ones((5,3))
b = np.ones((3,2))

z= np.dot(a,b)

print(z)



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [125]:
 #Given a 1D array, negate all elements which are between 3 and 8, in place.
z=np.arange(11)
print(z)
z[(3<z) & (z<=8) ]*=-1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [133]:
# sum(a)
# a is the list , it adds up all the numbers in the 
# list a and takes start to be 0, so returning 
# only the sum of the numbers in the list.
# sum(a, start)
# this returns the sum of the list + start 
numbers = [1,2,3,4,5,1,4,5] 
Sum = sum(numbers) 
print(Sum) 
  
# start = 10 
Sum = sum(numbers, 10) 
print(Sum) 

print(range(5))

print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))

25
35
range(0, 5)
10


In [154]:
z= np.arange(10)
print(z)
#x**y (x to the power y)
z=z**z
print(z)
#>>	Bitwise right shift	x>> 2 = 2 (0000 0010)
#2 << Z >> 2 (invalid)
#z < -z
1j*z
#z/1/1
#z<z>z invalid

[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


array([0.+1.00000000e+00j, 0.+1.00000000e+00j, 0.+4.00000000e+00j,
       0.+2.70000000e+01j, 0.+2.56000000e+02j, 0.+3.12500000e+03j,
       0.+4.66560000e+04j, 0.+8.23543000e+05j, 0.+1.67772160e+07j,
       0.+3.87420489e+08j])

In [161]:
#print(np.array(0) / np.array(0))
#print(np.array(0) // np.array(0)) 
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [163]:
# uniform() can also be used for generating multiple random numbers 
# that too with the desired shape which is not possible with .random()

Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 2.5625799  -9.41520515 -2.50488495 -2.47663283  8.27738151  9.86800923
 -3.16021911  5.94185597 -0.70918501 -9.24579683]
[  3. -10.  -3.  -3.   9.  10.  -4.   6.  -1. -10.]


In [168]:
#  30. How to find common values between two arrays?
z1 = np.random.randint(0,10,10)
print(z1)
z2 = np.random.randint(0,10,10)
print(z2)
print(np.intersect1d(z1,z2))


[2 5 9 6 8 1 4 5 0 0]
[2 1 4 1 0 6 9 3 1 9]
[0 1 2 4 6 9]


In [178]:
# 31. How to ignore all numpy warnings (not recommended)?
# Suicide mode on
#defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
defaults = np.seterr(**defaults)
Z = np.ones(1) / 0
#print(Z)

In [179]:
np.sqrt(-1) == np.emath.sqrt(-1) #???

False

In [181]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2019-02-05
2019-02-06
2019-02-07


In [182]:
#34. How to get all the dates corresponding to the month of July 2016? 
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [183]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [184]:
# 36. Extract the integer part of a random array using 5 different methods 
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4. 1. 2. 9. 9. 4. 1. 7. 0. 1.]
[4. 1. 2. 9. 9. 4. 1. 7. 0. 1.]
[4. 1. 2. 9. 9. 4. 1. 7. 0. 1.]
[4 1 2 9 9 4 1 7 0 1]
[4. 1. 2. 9. 9. 4. 1. 7. 0. 1.]


In [ ]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4
